# 👻  **Taller 3 - Limpieza y filtrado en pandas 🐼**

<img src="https://www.udistrital.edu.co/themes/custom/versh/images/default/preloader.png" align="left" width="192px" height="192px"/>
<img align="left" width="0" height="192px" hspace="10"/>

> Juan Felipe Rodríguez Galindo  - **COD. 20181020158**
[![Juan Felipe Rodriguez Galindo](https://img.shields.io/badge/Juferoga-github-br?style=flat-square)](https://gitlab.com/Juferoga)[![License](https://img.shields.io/badge/License-GPL_V.3-blue?style=flat-square)](https://www.gnu.org/licenses/gpl-3.0.html)


Introducción a la Ciencia de Datos

Desarrrollo del taller "TALLER DE LIMPIEZA Y FILTRADO BÁSICO" propuesto en la clase de introducción a la ciencia de datos.

## Taller


1. Importar un CSV desde Datos Abierto

2. Limpiar datos

Utilizar cada uno de los métodos de limpieza mostrados a continuación y comentar su efecto. 

**Nota: Si el data set no permite ver el efecto, se debe modificar el data set, de tal forma que el resultado de la ejecución de cada instrucción sea evidente.**

 
    df.isnull()
    df.dropna(axis=0, how='any') 
    df.dropna(axis=0, how='all')
    df.dropna(axis=1, how='any')
    df.fillna(value=3)
    df.fillna(df.mean())
    df.fillna(method='bfill', limit=1)

3. Filtrado y consulta de datos

- Utilizar cada uno de los filtros mostrados a continuación y comentar su efecto.

**Nota: Si el data set no permite ver el efecto, se debe modificar el data set, de tal forma que el resultado de la ejecución de cada instrucción sea evidente.**

    df['columna n'] >= valor
    df[df['columna n'] >= valor]
    df['columna n'][df['columna m'] >= valor]
    df[(df['columna n'] >= valor) & (df['columna m] >= valor)]

- Realizar consulta de datos empleando las siguientes instrucciones:

    1. Where
    2. Mask  (¿Cuál es la principal diferencia entre where y mask?)
    3. Isin     (¿Cuál es la diferencia de pasarle como parámetro una lista o un diccionario? )
    4. Query
    5. Eval

## **Desarrollo**

 ### Importando Pandas
 
 Biblioteca de software escrita como extensión de NumPy para manipulación y análisis de datos para el lenguaje de programación Python.

In [72]:
# Importamos la biblioteca pandas y le ponemos un alias para mayor utilizarlo de forma mas fácil

import pandas as pd
print ('pandas importado 👍')

pandas importado 👍

### 1) Importando el csv

Importamos el conjunto de datos que vallamos a utilizar para el desarrollo del taller

In [73]:
c_c19 = pd.read_csv('Casos_positivos_de_COVID-19_en_Colombia.csv')
print(c_c19)
print ('\n csv importado 👍')

       ID de caso    Fecha de notificación  Codigo DIVIPOLA  \
0               1  2020-03-02T00:00:00.000          11001.0
1               2  2020-03-06T00:00:00.000          76111.0
2               3  2020-03-07T00:00:00.000              NaN
3               4  2020-03-09T00:00:00.000              NaN
4               5  2020-03-09T00:00:00.000           5001.0
...           ...                      ...              ...
13605       13646  2020-05-06T00:00:00.000          13001.0
13606       13647  2020-05-10T00:00:00.000          13001.0
13607       13648  2020-05-10T00:00:00.000          13001.0
13608       13649  2020-05-10T00:00:00.000          13001.0
13609       13650  2020-05-11T00:00:00.000          13001.0

       Ciudad de ubicación Departamento o Distrito     atención  Edad Sexo  \
0              Bogotá D.C.              Bogotá D.C.  Recuperado    19    F
1      Guadalajara de Buga          Valle del Cauca  Recuperado    34    M
2                 Medellín                Antioquia  Recuperado    50    F
3                 Medellín                Antioquia  Recuperado    55    M
4                 Medellín                Antioquia  Recuperado    25    M
...                    ...                      ...         ...   ...  ...
13605  Cartagena de Indias      Cartagena D.T. y C.        Casa    47    F
13606  Cartagena de Indias      Cartagena D.T. y C.    Hospital    51    M
13607  Cartagena de Indias      Cartagena D.T. y C.        Casa    21    M
13608  Cartagena de Indias      Cartagena D.T. y C.        Casa    52    M
13609  Cartagena de Indias      Cartagena D.T. y C.        Casa    75    F

              Tipo      Estado País de procedencia                      FIS  \
0        Importado  Recuperado              Italia  2020-02-27T00:00:00.000
1        Importado  Recuperado              España  2020-03-04T00:00:00.000
2        Importado  Recuperado              España  2020-02-29T00:00:00.000
3      Relacionado  Recuperado            Colombia  2020-03-06T00:00:00.000
4      Relacionado  Recuperado            Colombia  2020-03-08T00:00:00.000
...            ...         ...                 ...                      ...
13605   En estudio        Leve            Colombia  2020-05-01T00:00:00.000
13606   En estudio    Moderado            Colombia  2020-05-02T00:00:00.000
13607   En estudio        Leve            Colombia  2020-05-07T00:00:00.000
13608   En estudio        Leve            Colombia  2020-05-08T00:00:00.000
13609   En estudio        Leve            Colombia  2020-05-02T00:00:00.000

      Fecha de muerte        Fecha diagnostico         Fecha recuperado  \
0               -   -  2020-03-06T00:00:00.000  2020-03-13T00:00:00.000
1                 NaN  2020-03-09T00:00:00.000  2020-03-19T00:00:00.000
2                 NaN  2020-03-09T00:00:00.000  2020-03-15T00:00:00.000
3                 NaN  2020-03-11T00:00:00.000  2020-03-26T00:00:00.000
4                 NaN  2020-03-11T00:00:00.000  2020-03-23T00:00:00.000
...               ...                      ...                      ...
13605             NaN  2020-05-14T00:00:00.000                      NaN
13606             NaN  2020-05-14T00:00:00.000                      NaN
13607             NaN  2020-05-14T00:00:00.000                      NaN
13608             NaN  2020-05-14T00:00:00.000                      NaN
13609             NaN  2020-05-14T00:00:00.000                      NaN

             fecha reporte web      NaN
0      2020-03-06T00:00:00.000      1.0
1      2020-03-09T00:00:00.000      NaN
2      2020-03-09T00:00:00.000      3.0
3      2020-03-11T00:00:00.000      4.0
4      2020-03-11T00:00:00.000      5.0
...                        ...      ...
13605  2020-05-14T00:00:00.000  13606.0
13606  2020-05-14T00:00:00.000  13607.0
13607  2020-05-14T00:00:00.000  13608.0
13608  2020-05-14T00:00:00.000  13609.0
13609  2020-05-14T00:00:00.000  13610.0

[13610 rows x 17 columns]

 csv importado 👍

## 2) Limpiando el .csv

Se limpiara el .csv utilizando las funciones y comentando el cambio.
- **c_c19.isnull()**

In [74]:
#print(c_c19.isnull())
c_c19.isnull()
#print(c_c19)

,ID de caso,Fecha de notificación,Codigo DIVIPOLA,Ciudad de ubicación,Departamento o Distrito,atención,Edad,Sexo,Tipo,Estado,País de procedencia,FIS,Fecha de muerte,Fecha diagnostico,Fecha recuperado,fecha reporte web,NaN
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True
2,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False
3,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13605,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False
13606,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False
13607,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False
13608,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False
13609,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False

El resultado arrojado por la función es **mostrar que campo esta lleno y cual no**, al que esta lleno se le asigna un booleano(*True*) en caso contrario se le asigna un *False* como **indicador** de que se encuentra vacio.
<hr>

## AXIS

![Axis example](https://railsware.com/blog/wp-content/uploads/2018/11/data-frame-axes.png)

- **c_c19.dropna(axis=0,how='any')**

In [75]:
#print(c_c19.dropna(axis=0,how='any'))
c_c19.dropna(axis=0,how='any')
#print(c_c19)

,ID de caso,Fecha de notificación,Codigo DIVIPOLA,Ciudad de ubicación,Departamento o Distrito,atención,Edad,Sexo,Tipo,Estado,País de procedencia,FIS,Fecha de muerte,Fecha diagnostico,Fecha recuperado,fecha reporte web,NaN
0,1,2020-03-02T00:00:00.000,11001.0,Bogotá D.C.,Bogotá D.C.,Recuperado,19,F,Importado,Recuperado,Italia,2020-02-27T00:00:00.000,- -,2020-03-06T00:00:00.000,2020-03-13T00:00:00.000,2020-03-06T00:00:00.000,1.0

El resultado arrojado por la función es **Elimina todas las filas donde halla un campo que no esta lleno**, el que esta lleno es el unico que se logra ver. Que este dentro del eje "y".
<hr>

- **c_c19.dropna(axis=0,how='all')**

In [76]:
#print(c_c19.dropna(axis=0,how='all'))
c_c19.dropna(axis=0,how='all')
#print(c_c19)

,ID de caso,Fecha de notificación,Codigo DIVIPOLA,Ciudad de ubicación,Departamento o Distrito,atención,Edad,Sexo,Tipo,Estado,País de procedencia,FIS,Fecha de muerte,Fecha diagnostico,Fecha recuperado,fecha reporte web,NaN
0,1,2020-03-02T00:00:00.000,11001.0,Bogotá D.C.,Bogotá D.C.,Recuperado,19,F,Importado,Recuperado,Italia,2020-02-27T00:00:00.000,- -,2020-03-06T00:00:00.000,2020-03-13T00:00:00.000,2020-03-06T00:00:00.000,1.0
1,2,2020-03-06T00:00:00.000,76111.0,Guadalajara de Buga,Valle del Cauca,Recuperado,34,M,Importado,Recuperado,España,2020-03-04T00:00:00.000,NaN,2020-03-09T00:00:00.000,2020-03-19T00:00:00.000,2020-03-09T00:00:00.000,NaN
2,3,2020-03-07T00:00:00.000,NaN,Medellín,Antioquia,Recuperado,50,F,Importado,Recuperado,España,2020-02-29T00:00:00.000,NaN,2020-03-09T00:00:00.000,2020-03-15T00:00:00.000,2020-03-09T00:00:00.000,3.0
3,4,2020-03-09T00:00:00.000,NaN,Medellín,Antioquia,Recuperado,55,M,Relacionado,Recuperado,Colombia,2020-03-06T00:00:00.000,NaN,2020-03-11T00:00:00.000,2020-03-26T00:00:00.000,2020-03-11T00:00:00.000,4.0
4,5,2020-03-09T00:00:00.000,5001.0,Medellín,Antioquia,Recuperado,25,M,Relacionado,Recuperado,Colombia,2020-03-08T00:00:00.000,NaN,2020-03-11T00:00:00.000,2020-03-23T00:00:00.000,2020-03-11T00:00:00.000,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13605,13646,2020-05-06T00:00:00.000,13001.0,Cartagena de Indias,Cartagena D.T. y C.,Casa,47,F,En estudio,Leve,Colombia,2020-05-01T00:00:00.000,NaN,2020-05-14T00:00:00.000,NaN,2020-05-14T00:00:00.000,13606.0
13606,13647,2020-05-10T00:00:00.000,13001.0,Cartagena de Indias,Cartagena D.T. y C.,Hospital,51,M,En estudio,Moderado,Colombia,2020-05-02T00:00:00.000,NaN,2020-05-14T00:00:00.000,NaN,2020-05-14T00:00:00.000,13607.0
13607,13648,2020-05-10T00:00:00.000,13001.0,Cartagena de Indias,Cartagena D.T. y C.,Casa,21,M,En estudio,Leve,Colombia,2020-05-07T00:00:00.000,NaN,2020-05-14T00:00:00.000,NaN,2020-05-14T00:00:00.000,13608.0
13608,13649,2020-05-10T00:00:00.000,13001.0,Cartagena de Indias,Cartagena D.T. y C.,Casa,52,M,En estudio,Leve,Colombia,2020-05-08T00:00:00.000,NaN,2020-05-14T00:00:00.000,NaN,2020-05-14T00:00:00.000,13609.0
13609,13650,2020-05-11T00:00:00.000,13001.0,Cartagena de Indias,Cartagena D.T. y C.,Casa,75,F,En estudio,Leve,Colombia,2020-05-02T00:00:00.000,NaN,2020-05-14T00:00:00.000,NaN,2020-05-14T00:00:00.000,13610.0

El resultado arrojado por la función es **Eliminar el campo que no esta lleno**, el que esta lleno es el unico que se logra ver, en caso contrario no se muestra en la tabla resultante. Dentro del eje "X".
**how=alll** quiere decir todos los registros
<hr>

- **c_c19.dropna(axis=1,how='any')**

In [77]:
#print(c_c19.dropna(axis=1,how='any'))
c_c19.dropna(axis=1,how='any')
#print(c_c19)

,ID de caso,Fecha de notificación,Ciudad de ubicación,Departamento o Distrito,Edad,Sexo,Tipo,País de procedencia,FIS,Fecha diagnostico,fecha reporte web
0,1,2020-03-02T00:00:00.000,Bogotá D.C.,Bogotá D.C.,19,F,Importado,Italia,2020-02-27T00:00:00.000,2020-03-06T00:00:00.000,2020-03-06T00:00:00.000
1,2,2020-03-06T00:00:00.000,Guadalajara de Buga,Valle del Cauca,34,M,Importado,España,2020-03-04T00:00:00.000,2020-03-09T00:00:00.000,2020-03-09T00:00:00.000
2,3,2020-03-07T00:00:00.000,Medellín,Antioquia,50,F,Importado,España,2020-02-29T00:00:00.000,2020-03-09T00:00:00.000,2020-03-09T00:00:00.000
3,4,2020-03-09T00:00:00.000,Medellín,Antioquia,55,M,Relacionado,Colombia,2020-03-06T00:00:00.000,2020-03-11T00:00:00.000,2020-03-11T00:00:00.000
4,5,2020-03-09T00:00:00.000,Medellín,Antioquia,25,M,Relacionado,Colombia,2020-03-08T00:00:00.000,2020-03-11T00:00:00.000,2020-03-11T00:00:00.000
...,...,...,...,...,...,...,...,...,...,...,...
13605,13646,2020-05-06T00:00:00.000,Cartagena de Indias,Cartagena D.T. y C.,47,F,En estudio,Colombia,2020-05-01T00:00:00.000,2020-05-14T00:00:00.000,2020-05-14T00:00:00.000
13606,13647,2020-05-10T00:00:00.000,Cartagena de Indias,Cartagena D.T. y C.,51,M,En estudio,Colombia,2020-05-02T00:00:00.000,2020-05-14T00:00:00.000,2020-05-14T00:00:00.000
13607,13648,2020-05-10T00:00:00.000,Cartagena de Indias,Cartagena D.T. y C.,21,M,En estudio,Colombia,2020-05-07T00:00:00.000,2020-05-14T00:00:00.000,2020-05-14T00:00:00.000
13608,13649,2020-05-10T00:00:00.000,Cartagena de Indias,Cartagena D.T. y C.,52,M,En estudio,Colombia,2020-05-08T00:00:00.000,2020-05-14T00:00:00.000,2020-05-14T00:00:00.000
13609,13650,2020-05-11T00:00:00.000,Cartagena de Indias,Cartagena D.T. y C.,75,F,En estudio,Colombia,2020-05-02T00:00:00.000,2020-05-14T00:00:00.000,2020-05-14T00:00:00.000

El resultado arrojado por la función es **Eliminar la columna donde halla un campo que no esta lleno**, el que esta lleno es el unico que se logra ver.

Limpia (axis=1) la columna para cualquier valor que este vacio (how='any')
<hr>

- **c_c19.fillna(value=0)**

In [78]:
#print(c_c19.fillna(value=0))
c_c19.fillna(value=0)
#print(c_c19)

,ID de caso,Fecha de notificación,Codigo DIVIPOLA,Ciudad de ubicación,Departamento o Distrito,atención,Edad,Sexo,Tipo,Estado,País de procedencia,FIS,Fecha de muerte,Fecha diagnostico,Fecha recuperado,fecha reporte web,NaN
0,1,2020-03-02T00:00:00.000,11001.0,Bogotá D.C.,Bogotá D.C.,Recuperado,19,F,Importado,Recuperado,Italia,2020-02-27T00:00:00.000,- -,2020-03-06T00:00:00.000,2020-03-13T00:00:00.000,2020-03-06T00:00:00.000,1.0
1,2,2020-03-06T00:00:00.000,76111.0,Guadalajara de Buga,Valle del Cauca,Recuperado,34,M,Importado,Recuperado,España,2020-03-04T00:00:00.000,0,2020-03-09T00:00:00.000,2020-03-19T00:00:00.000,2020-03-09T00:00:00.000,0.0
2,3,2020-03-07T00:00:00.000,0.0,Medellín,Antioquia,Recuperado,50,F,Importado,Recuperado,España,2020-02-29T00:00:00.000,0,2020-03-09T00:00:00.000,2020-03-15T00:00:00.000,2020-03-09T00:00:00.000,3.0
3,4,2020-03-09T00:00:00.000,0.0,Medellín,Antioquia,Recuperado,55,M,Relacionado,Recuperado,Colombia,2020-03-06T00:00:00.000,0,2020-03-11T00:00:00.000,2020-03-26T00:00:00.000,2020-03-11T00:00:00.000,4.0
4,5,2020-03-09T00:00:00.000,5001.0,Medellín,Antioquia,Recuperado,25,M,Relacionado,Recuperado,Colombia,2020-03-08T00:00:00.000,0,2020-03-11T00:00:00.000,2020-03-23T00:00:00.000,2020-03-11T00:00:00.000,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13605,13646,2020-05-06T00:00:00.000,13001.0,Cartagena de Indias,Cartagena D.T. y C.,Casa,47,F,En estudio,Leve,Colombia,2020-05-01T00:00:00.000,0,2020-05-14T00:00:00.000,0,2020-05-14T00:00:00.000,13606.0
13606,13647,2020-05-10T00:00:00.000,13001.0,Cartagena de Indias,Cartagena D.T. y C.,Hospital,51,M,En estudio,Moderado,Colombia,2020-05-02T00:00:00.000,0,2020-05-14T00:00:00.000,0,2020-05-14T00:00:00.000,13607.0
13607,13648,2020-05-10T00:00:00.000,13001.0,Cartagena de Indias,Cartagena D.T. y C.,Casa,21,M,En estudio,Leve,Colombia,2020-05-07T00:00:00.000,0,2020-05-14T00:00:00.000,0,2020-05-14T00:00:00.000,13608.0
13608,13649,2020-05-10T00:00:00.000,13001.0,Cartagena de Indias,Cartagena D.T. y C.,Casa,52,M,En estudio,Leve,Colombia,2020-05-08T00:00:00.000,0,2020-05-14T00:00:00.000,0,2020-05-14T00:00:00.000,13609.0
13609,13650,2020-05-11T00:00:00.000,13001.0,Cartagena de Indias,Cartagena D.T. y C.,Casa,75,F,En estudio,Leve,Colombia,2020-05-02T00:00:00.000,0,2020-05-14T00:00:00.000,0,2020-05-14T00:00:00.000,13610.0

El resultado arrojado por la función es el **cambio de los valores NaN por un valor determinado**.
<hr>

- **c_c19.fillna(c_c19.mean())**

In [79]:
#print(c_c19.fillna(c_c19.mean()))
c_c19.fillna(c_c19.mean())
#print(c_c19)

,ID de caso,Fecha de notificación,Codigo DIVIPOLA,Ciudad de ubicación,Departamento o Distrito,atención,Edad,Sexo,Tipo,Estado,País de procedencia,FIS,Fecha de muerte,Fecha diagnostico,Fecha recuperado,fecha reporte web,NaN
0,1,2020-03-02T00:00:00.000,11001.000000,Bogotá D.C.,Bogotá D.C.,Recuperado,19,F,Importado,Recuperado,Italia,2020-02-27T00:00:00.000,- -,2020-03-06T00:00:00.000,2020-03-13T00:00:00.000,2020-03-06T00:00:00.000,1.000000
1,2,2020-03-06T00:00:00.000,76111.000000,Guadalajara de Buga,Valle del Cauca,Recuperado,34,M,Importado,Recuperado,España,2020-03-04T00:00:00.000,NaN,2020-03-09T00:00:00.000,2020-03-19T00:00:00.000,2020-03-09T00:00:00.000,6805.999927
2,3,2020-03-07T00:00:00.000,32091.430871,Medellín,Antioquia,Recuperado,50,F,Importado,Recuperado,España,2020-02-29T00:00:00.000,NaN,2020-03-09T00:00:00.000,2020-03-15T00:00:00.000,2020-03-09T00:00:00.000,3.000000
3,4,2020-03-09T00:00:00.000,32091.430871,Medellín,Antioquia,Recuperado,55,M,Relacionado,Recuperado,Colombia,2020-03-06T00:00:00.000,NaN,2020-03-11T00:00:00.000,2020-03-26T00:00:00.000,2020-03-11T00:00:00.000,4.000000
4,5,2020-03-09T00:00:00.000,5001.000000,Medellín,Antioquia,Recuperado,25,M,Relacionado,Recuperado,Colombia,2020-03-08T00:00:00.000,NaN,2020-03-11T00:00:00.000,2020-03-23T00:00:00.000,2020-03-11T00:00:00.000,5.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13605,13646,2020-05-06T00:00:00.000,13001.000000,Cartagena de Indias,Cartagena D.T. y C.,Casa,47,F,En estudio,Leve,Colombia,2020-05-01T00:00:00.000,NaN,2020-05-14T00:00:00.000,NaN,2020-05-14T00:00:00.000,13606.000000
13606,13647,2020-05-10T00:00:00.000,13001.000000,Cartagena de Indias,Cartagena D.T. y C.,Hospital,51,M,En estudio,Moderado,Colombia,2020-05-02T00:00:00.000,NaN,2020-05-14T00:00:00.000,NaN,2020-05-14T00:00:00.000,13607.000000
13607,13648,2020-05-10T00:00:00.000,13001.000000,Cartagena de Indias,Cartagena D.T. y C.,Casa,21,M,En estudio,Leve,Colombia,2020-05-07T00:00:00.000,NaN,2020-05-14T00:00:00.000,NaN,2020-05-14T00:00:00.000,13608.000000
13608,13649,2020-05-10T00:00:00.000,13001.000000,Cartagena de Indias,Cartagena D.T. y C.,Casa,52,M,En estudio,Leve,Colombia,2020-05-08T00:00:00.000,NaN,2020-05-14T00:00:00.000,NaN,2020-05-14T00:00:00.000,13609.000000
13609,13650,2020-05-11T00:00:00.000,13001.000000,Cartagena de Indias,Cartagena D.T. y C.,Casa,75,F,En estudio,Leve,Colombia,2020-05-02T00:00:00.000,NaN,2020-05-14T00:00:00.000,NaN,2020-05-14T00:00:00.000,13610.000000

El resultado arrojado por la función es el **cambio de los valores NaN por un valor determinado**.
<hr>

- **c_c19.fillna(method='bfill',limit=1)**

In [80]:
#print(c_c19.fillna(method='bfill',limit=1))
c_c19.fillna(method='bfill',limit=1)
#print(c_c19)

,ID de caso,Fecha de notificación,Codigo DIVIPOLA,Ciudad de ubicación,Departamento o Distrito,atención,Edad,Sexo,Tipo,Estado,País de procedencia,FIS,Fecha de muerte,Fecha diagnostico,Fecha recuperado,fecha reporte web,NaN
0,1,2020-03-02T00:00:00.000,11001.0,Bogotá D.C.,Bogotá D.C.,Recuperado,19,F,Importado,Recuperado,Italia,2020-02-27T00:00:00.000,- -,2020-03-06T00:00:00.000,2020-03-13T00:00:00.000,2020-03-06T00:00:00.000,1.0
1,2,2020-03-06T00:00:00.000,76111.0,Guadalajara de Buga,Valle del Cauca,Recuperado,34,M,Importado,Recuperado,España,2020-03-04T00:00:00.000,NaN,2020-03-09T00:00:00.000,2020-03-19T00:00:00.000,2020-03-09T00:00:00.000,3.0
2,3,2020-03-07T00:00:00.000,NaN,Medellín,Antioquia,Recuperado,50,F,Importado,Recuperado,España,2020-02-29T00:00:00.000,NaN,2020-03-09T00:00:00.000,2020-03-15T00:00:00.000,2020-03-09T00:00:00.000,3.0
3,4,2020-03-09T00:00:00.000,5001.0,Medellín,Antioquia,Recuperado,55,M,Relacionado,Recuperado,Colombia,2020-03-06T00:00:00.000,NaN,2020-03-11T00:00:00.000,2020-03-26T00:00:00.000,2020-03-11T00:00:00.000,4.0
4,5,2020-03-09T00:00:00.000,5001.0,Medellín,Antioquia,Recuperado,25,M,Relacionado,Recuperado,Colombia,2020-03-08T00:00:00.000,NaN,2020-03-11T00:00:00.000,2020-03-23T00:00:00.000,2020-03-11T00:00:00.000,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13605,13646,2020-05-06T00:00:00.000,13001.0,Cartagena de Indias,Cartagena D.T. y C.,Casa,47,F,En estudio,Leve,Colombia,2020-05-01T00:00:00.000,NaN,2020-05-14T00:00:00.000,NaN,2020-05-14T00:00:00.000,13606.0
13606,13647,2020-05-10T00:00:00.000,13001.0,Cartagena de Indias,Cartagena D.T. y C.,Hospital,51,M,En estudio,Moderado,Colombia,2020-05-02T00:00:00.000,NaN,2020-05-14T00:00:00.000,NaN,2020-05-14T00:00:00.000,13607.0
13607,13648,2020-05-10T00:00:00.000,13001.0,Cartagena de Indias,Cartagena D.T. y C.,Casa,21,M,En estudio,Leve,Colombia,2020-05-07T00:00:00.000,NaN,2020-05-14T00:00:00.000,NaN,2020-05-14T00:00:00.000,13608.0
13608,13649,2020-05-10T00:00:00.000,13001.0,Cartagena de Indias,Cartagena D.T. y C.,Casa,52,M,En estudio,Leve,Colombia,2020-05-08T00:00:00.000,NaN,2020-05-14T00:00:00.000,NaN,2020-05-14T00:00:00.000,13609.0
13609,13650,2020-05-11T00:00:00.000,13001.0,Cartagena de Indias,Cartagena D.T. y C.,Casa,75,F,En estudio,Leve,Colombia,2020-05-02T00:00:00.000,NaN,2020-05-14T00:00:00.000,NaN,2020-05-14T00:00:00.000,13610.0

El resultado arrojado por la función es el **Completa los campos vacios, con el valor por debajo del campo vacío** y solo remplazara el primer campo que encuentre vacio por el método limit=1.
<hr>

## 2) Filtrado y consulta de datos

Utilizar cada filtro de consulta de datos, y escribir lo que hacen.
- **c_c19['atención'] >= 12**

In [81]:
print(c_c19['Edad'] >= 55)
#print(c_c19)

0        False
1        False
2        False
3         True
4        False
         ...
13605    False
13606    False
13607    False
13608    False
13609     True
Name: Edad, Length: 13610, dtype: bool

El resultado de la función es traer todos los registros que cumplan con la condición de estar en la tabla edad y ser mayor de 55 y **mostrar un booleano si se cumple la condición o no**.
<hr>

- **c_c19[c_c19['Edad'] >= 55]**

In [82]:
print(c_c19[c_c19['Edad'] >= 55])
#print(c_c19)

       ID de caso    Fecha de notificación  Codigo DIVIPOLA  \
3               4  2020-03-09T00:00:00.000              NaN
6               7  2020-03-08T00:00:00.000          13001.0
11             12  2020-03-10T00:00:00.000          41001.0
12             13  2020-03-10T00:00:00.000          41001.0
15             16  2020-03-11T00:00:00.000              NaN
...           ...                      ...              ...
13574       13615  2020-05-07T00:00:00.000          47001.0
13578       13619  2020-05-08T00:00:00.000          47189.0
13580       13621  2020-05-11T00:00:00.000          13836.0
13601       13642  2020-05-10T00:00:00.000           5001.0
13609       13650  2020-05-11T00:00:00.000          13001.0

       Ciudad de ubicación Departamento o Distrito     atención  Edad Sexo  \
3                 Medellín                Antioquia  Recuperado    55    M
6      Cartagena de Indias      Cartagena D.T. y C.  Recuperado    85    F
11                   Neiva                    Huila  Recuperado    74    F
12                   Neiva                    Huila  Recuperado    68    F
15             Bogotá D.C.              Bogotá D.C.  Recuperado    61    F
...                    ...                      ...         ...   ...  ...
13574          Santa Marta    Santa Marta D.T. y C.        Casa    55    M
13578              Ciénaga                Magdalena        Casa    89    M
13580              Turbaco                  Bolívar        Casa    87    F
13601             Medellín                Antioquia        Casa    78    M
13609  Cartagena de Indias      Cartagena D.T. y C.        Casa    75    F

              Tipo        Estado        País de procedencia  \
3      Relacionado    Recuperado                   Colombia
6        Importado    Recuperado  Estados Unidos de América
11       Importado    Recuperado                     Italia
12     Relacionado    Recuperado                   Colombia
15       Importado    Recuperado                     Italia
...            ...           ...                        ...
13574   En estudio          Leve                   Colombia
13578   En estudio          Leve                   Colombia
13580  Relacionado  Asintomático                   Colombia
13601  Relacionado  Asintomático                   Colombia
13609   En estudio          Leve                   Colombia

                           FIS Fecha de muerte        Fecha diagnostico  \
3      2020-03-06T00:00:00.000             NaN  2020-03-11T00:00:00.000
6      2020-03-02T00:00:00.000             NaN  2020-03-11T00:00:00.000
11     2020-03-06T00:00:00.000             NaN  2020-03-12T00:00:00.000
12     2020-03-06T00:00:00.000             NaN  2020-03-12T00:00:00.000
15     2020-03-08T00:00:00.000             NaN  2020-03-13T00:00:00.000
...                        ...             ...                      ...
13574  2020-05-03T00:00:00.000             NaN  2020-05-14T00:00:00.000
13578  2020-05-04T00:00:00.000             NaN  2020-05-14T00:00:00.000
13580             Asintomático             NaN  2020-05-14T00:00:00.000
13601             Asintomático             NaN  2020-05-14T00:00:00.000
13609  2020-05-02T00:00:00.000             NaN  2020-05-14T00:00:00.000

              Fecha recuperado        fecha reporte web      NaN
3      2020-03-26T00:00:00.000  2020-03-11T00:00:00.000      4.0
6      2020-03-17T00:00:00.000  2020-03-11T00:00:00.000      7.0
11     2020-04-09T00:00:00.000  2020-03-12T00:00:00.000     12.0
12     2020-03-30T00:00:00.000  2020-03-12T00:00:00.000     13.0
15     2020-03-23T00:00:00.000  2020-03-13T00:00:00.000     16.0
...                        ...                      ...      ...
13574                      NaN  2020-05-14T00:00:00.000  13575.0
13578                      NaN  2020-05-14T00:00:00.000  13579.0
13580                      NaN  2020-05-14T00:00:00.000  13581.0
13601                      NaN  2020-05-14T00:00:00.000  13602.0
13609                      NaN  2020-05-14T00:00:00.000  13610.0

[3029 rows x 17 columns]

El resultado de la función es traer **todos los registros que cumplan con la condición** de estar en la tabla edad y ser mayor de 55.
<hr>

- **c_c19['atención'][c_c19['Edad'] >= 55]**

In [83]:
print(c_c19['atención'][c_c19['Edad'] >= 55])
#print(c_c19)

3        Recuperado
6        Recuperado
11       Recuperado
12       Recuperado
15       Recuperado
            ...
13574          Casa
13578          Casa
13580          Casa
13601          Casa
13609          Casa
Name: atención, Length: 3029, dtype: object

El resultado de la **función es traer todos los registros de la columna atención que cumplan con la condición de estar en la tabla edad** y ser mayor de 55 y y mostrar un booleano si se cumplen o no.
<hr>

- **c_c19[(c_c19['ID de caso'] >= 13544)&(c_c19['Edad'] >= 55)]**

In [84]:
#print(c_c19[(c_c19['ID de caso'] >= 13544)&(c_c19['Edad'] >= 55)])
c_c19[(c_c19['ID de caso'] >= 11)&(c_c19['Edad'] >= 95)]
#print(c_c19)

,ID de caso,Fecha de notificación,Codigo DIVIPOLA,Ciudad de ubicación,Departamento o Distrito,atención,Edad,Sexo,Tipo,Estado,País de procedencia,FIS,Fecha de muerte,Fecha diagnostico,Fecha recuperado,fecha reporte web,NaN
1245,1246,2020-03-29T00:00:00.000,11001.0,Bogotá D.C.,Bogotá D.C.,Recuperado,95,F,En estudio,Recuperado,Colombia,2020-03-28T00:00:00.000,NaN,2020-04-03T00:00:00.000,2020-04-14T00:00:00.000,2020-04-03T00:00:00.000,1246.0
1482,1483,2020-04-03T00:00:00.000,11001.0,Bogotá D.C.,Bogotá D.C.,Fallecido,97,F,En estudio,Fallecido,Colombia,2020-03-30T00:00:00.000,2020-04-14T00:00:00.000,2020-04-05T00:00:00.000,NaN,2020-04-05T00:00:00.000,1483.0
1809,1810,2020-04-04T00:00:00.000,47001.0,Santa Marta,Santa Marta D.T. y C.,Fallecido,96,F,En estudio,Fallecido,Colombia,2020-03-28T00:00:00.000,2020-04-08T00:00:00.000,2020-04-08T00:00:00.000,NaN,2020-04-08T00:00:00.000,1810.0
2171,2172,2020-03-28T00:00:00.000,54498.0,Ocaña,Norte de Santander,Fallecido,98,M,En estudio,Fallecido,Colombia,2020-03-24T00:00:00.000,2020-03-28T00:00:00.000,2020-04-09T00:00:00.000,NaN,2020-04-09T00:00:00.000,2172.0
3054,3055,2020-04-05T00:00:00.000,11001.0,Bogotá D.C.,Bogotá D.C.,Fallecido,97,F,En estudio,Fallecido,Colombia,2020-04-05T00:00:00.000,2020-04-13T00:00:00.000,2020-04-15T00:00:00.000,NaN,2020-04-15T00:00:00.000,3055.0
3757,3758,2020-04-12T00:00:00.000,11001.0,Bogotá D.C.,Bogotá D.C.,Hospital,103,F,En estudio,Moderado,Colombia,2020-04-11T00:00:00.000,NaN,2020-04-19T00:00:00.000,NaN,2020-04-19T00:00:00.000,3758.0
3990,3991,2020-04-14T00:00:00.000,76001.0,Cali,Valle del Cauca,Fallecido,95,F,En estudio,Fallecido,Colombia,2020-04-09T00:00:00.000,2020-04-23T00:00:00.000,2020-04-21T00:00:00.000,NaN,2020-04-21T00:00:00.000,3991.0
5300,5341,2020-04-03T00:00:00.000,11001.0,Bogotá D.C.,Bogotá D.C.,Fallecido,95,F,En estudio,Fallecido,Colombia,2020-04-03T00:00:00.000,2020-04-03T00:00:00.000,2020-04-26T00:00:00.000,NaN,2020-04-26T00:00:00.000,5301.0
5480,5521,2020-04-18T00:00:00.000,11001.0,Bogotá D.C.,Bogotá D.C.,Casa,96,F,En estudio,Leve,Colombia,2020-04-09T00:00:00.000,NaN,2020-04-27T00:00:00.000,NaN,2020-04-27T00:00:00.000,5481.0
5541,5582,2020-04-26T00:00:00.000,41001.0,Neiva,Huila,Hospital,96,F,Relacionado,Moderado,Colombia,2020-04-01T00:00:00.000,NaN,2020-04-27T00:00:00.000,NaN,2020-04-27T00:00:00.000,5542.0
6914,6955,2020-04-11T00:00:00.000,11001.0,Bogotá D.C.,Bogotá D.C.,Fallecido,95,F,En estudio,Fallecido,Colombia,2020-04-11T00:00:00.000,2020-04-26T00:00:00.000,2020-05-01T00:00:00.000,NaN,2020-05-01T00:00:00.000,6915.0
6967,7008,2020-04-28T00:00:00.000,13001.0,Cartagena de Indias,Cartagena D.T. y C.,Casa,96,F,Relacionado,Leve,Colombia,2020-04-24T00:00:00.000,NaN,2020-05-02T00:00:00.000,NaN,2020-05-02T00:00:00.000,6968.0
8246,8287,2020-05-02T00:00:00.000,8001.0,Barranquilla,Barranquilla D.E.,Hospital UCI,100,F,En estudio,Grave,Colombia,2020-04-01T00:00:00.000,NaN,2020-05-05T00:00:00.000,NaN,2020-05-05T00:00:00.000,8247.0
9771,9812,2020-04-26T00:00:00.000,11001.0,Bogotá D.C.,Bogotá D.C.,Hospital,96,F,En estudio,Moderado,Colombia,2020-04-26T00:00:00.000,NaN,2020-05-08T00:00:00.000,NaN,2020-05-08T00:00:00.000,9772.0

El resultado de la **función es traer todos los registros de todas las columnas atención que cumplan con las dos condiciones**.
<hr>

#### Consultas

Realizar consultas de datos empleando
- **where ...**

In [85]:
Num = pd.read_csv('Numero_de_Habitantes_por_Barrios_Rovira.csv')
print ('\n csv importado x2 👍')
#print(Num)

Num.where(Num > 64)

 csv importado x2 👍

    NUMERO DE HABITANTES  GENERO MASCULINO  GENERO FEMENINO
0                     98               NaN              NaN
1                    972             466.0            506.0
2                    836             402.0            434.0
3                    506             251.0            255.0
4                    126               NaN              NaN
5                    460             231.0            229.0
6                    821             399.0            422.0
7                   1436             691.0            745.0
8                    424             223.0            201.0
9                   1015             490.0            525.0
10                   410             223.0            187.0
11                  1320             628.0            692.0
12                   252             121.0            131.0
13                  1536             731.0            805.0

El resultado de la **función es reemplazar con NaN que cumplan con las condiciones dadas**.
<hr>

- **MASK ...**

In [86]:
Num.mask(Num > 64)

    NUMERO DE HABITANTES  GENERO MASCULINO  GENERO FEMENINO
0                    NaN              50.0             48.0
1                    NaN               NaN              NaN
2                    NaN               NaN              NaN
3                    NaN               NaN              NaN
4                    NaN              64.0             62.0
5                    NaN               NaN              NaN
6                    NaN               NaN              NaN
7                    NaN               NaN              NaN
8                    NaN               NaN              NaN
9                    NaN               NaN              NaN
10                   NaN               NaN              NaN
11                   NaN               NaN              NaN
12                   NaN               NaN              NaN
13                   NaN               NaN              NaN

El resultado de la **función es el contrario de la funcion where**.
<hr>

- **IsIn ...**

In [87]:
Num.isin([2,3,56,98])

    NUMERO DE HABITANTES  GENERO MASCULINO  GENERO FEMENINO
0                   True             False            False
1                  False             False            False
2                  False             False            False
3                  False             False            False
4                  False             False            False
5                  False             False            False
6                  False             False            False
7                  False             False            False
8                  False             False            False
9                  False             False            False
10                 False             False            False
11                 False             False            False
12                 False             False            False
13                 False             False            False

El resultado de la **función es traer todos los registros y asisgnar verdadero si se cumple que los valores del DF estan en la lista que suministramos**.
<hr>

- **Query ...**

In [88]:
Num.columns = Num.columns.str.replace(" ", "_") # busqueda más simple con _ en vez de " "
query = list(Num)[0] + ">" +list(Num)[1]
print(query)
Num.query('NUMERO_DE_HABITANTES > GENERO_MASCULINO')

NUMERO_DE_HABITANTES>GENERO_MASCULINO

    NUMERO_DE_HABITANTES  GENERO_MASCULINO  GENERO_FEMENINO
0                     98                50               48
1                    972               466              506
2                    836               402              434
3                    506               251              255
4                    126                64               62
5                    460               231              229
6                    821               399              422
7                   1436               691              745
8                    424               223              201
9                   1015               490              525
10                   410               223              187
11                  1320               628              692
12                   252               121              131
13                  1536               731              805

La función Query trae un **dataFrame con los registros que cumplan la condición del query**.<hr>

- **Eval ...**

In [91]:
print(query)
Num.eval('NUMERO_DE_HABITANTES-GENERO_MASCULINO')

NUMERO_DE_HABITANTES>GENERO_MASCULINO

0      48
1     506
2     434
3     255
4      62
5     229
6     422
7     745
8     201
9     525
10    187
11    692
12    131
13    805
dtype: int64

La función Eval trae un **dataFrame con los registros elimnados de las columnas que pedimos y muestra su valor en una nueva columna**.<hr>

                             Fin Taller - Limpieza y filtrado en pandas🐼
> Juan Felipe Rodríguez Galindo  - **COD. 20181020158**